config/routes.rb
FF::Application.routes.draw do
  match 'auth/:provider/callback',
    :to => 'sessions#create',
    :via => [:get, :post]

  match 'signout',
    :to => 'sessions#destroy',
    :as => 'signout',
    :via => [:get, :post]


  resources :users, :only => :index

  resources :accomplishments do
    resources :plus_ones
  end
  resources :suggestions

  get '/:username', :to => 'users#index', :as => 'user'
  get '/:username/stats', :to => 'stats#index', :as => 'user_stats'

  root to: 'application#index'
end

app/models/accomplishment.rb
class Accomplishment < ActiveRecord::Base
  include Twitter::Extractor

  belongs_to :poster, :class_name => User
  belongs_to :receiver, :class_name => User

  has_many :plus_ones
  
  attr_accessible :description, :poster, :receiver
  attr_accessible :poster_id, :receiver_id 

  acts_as_taggable

  validates_length_of :description, :maximum => 140
  validates_presence_of :description, :poster, :receiver
  validate :poster_cannot_be_receiver

  before_save :parse_tags
 
  def poster_cannot_be_receiver
    errors.add(:receiver, 'cannot be yourself') if poster == receiver
  end

  def self.latest
    order 'created_at DESC'
  end

  private

  def parse_tags
    tag_list.add(extract_hashtags(description))
  end
end

app/controllers/accomplishments_controller.rb
class AccomplishmentsController < ApplicationController
  def create
    raw = params[:accomplishment]
    description = raw[:description]
    receiver = User.where(:username => raw[:receiver_username]).first
    @accomplishment = current_user.report_accomplishment(description, receiver)
    if @accomplishment.valid?
      Notifier.accomplishment(@accomplishment).deliver
      redirect_to referer, :notice => 'Accomplishment reported'
    else
      redirect_to referer
    end
  end

  def destroy
    acc = Accomplishment.find_by_id(params[:id])
    current_user.delete_accomplishment(acc)
    redirect_to referer, :notice => 'Accomplishment removed'
  end
end

app/helpers/accomplishments_helper.rb
module AccomplishmentsHelper

  def description_max_length
    Accomplishment.validators_on(:description).find do |validator|
      validator.class == ActiveModel::Validations::LengthValidator
    end.options[:maximum]
  end

end

app/views/accomplishments/_index.slim
section#latest-accomplishments
  h1 Latest Accomplishments
  - if @tag
    span#tag-name ##{@tag}

  = will_paginate @accomplishments
  ul
    - if @accomplishments.empty?
      = image_tag 'forever-alone.png', :id => 'forever-alone', :alt => 'Forever Alone!', :title => 'Forever Alone!'
    - else
      - @accomplishments.each do |acc|
        li.accomplishment itemscope='' itemtype='http://schema.org/Review'

          div itemprop='itemReviewed' itemscope='' itemtype='http://schema.org/Person'
            = gravatar_image_tag(acc.receiver.email, itemprop:'image',
              alt: acc.receiver.username, gravatar: { secure: true, size: 50 })
            = link_to acc.receiver.username, user_path(acc.receiver.username), :itemprop => 'name'

          p itemprop='description' 
            = truncate(auto_link_hashtags(acc.description, :hashtag_url_base=>'/?tag='), length: 310).html_safe

          = button_to '+1', accomplishment_plus_ones_path(acc), 
            :method => :post, :class => 'plus-one', 
            :disabled => !current_user.allowed_to_plus_one?(acc)

          span.plus-one-counter 
            = acc.plus_ones.count
            ul
              - acc.plus_ones.each do |p1|
                li
                  = link_to user_path(p1.user.username) do
                    = gravatar_image_tag(p1.user.email,
                      alt: p1.user.username, gravatar: { secure: true, size: 20 })
                    span = p1.user.username


          time itemprop='datePublished' datetime=acc.updated_at.utc.iso8601
            span.day = acc.updated_at.day
            span.month = acc.updated_at.strftime '%b'
            span.year = acc.updated_at.year

          - if current_user.allowed_to_delete?(acc)
            = button_to '✕', acc, :method => :delete, 
              :confirm => 'Are you sure?', :class => 'remove'

          span itemprop='author'
            | by 
            = link_to acc.poster.username, user_path(acc.poster.username)

  = will_paginate @accomplishments

app/views/accomplishments/_new.slim
= form_for(@accomplishment) do |f|
  p#congratulate
    | Congratulate 
    = f.text_field :receiver_username,
      :placeholder => 'your peer',
      :required => true,
      :maxlength => '8',
      :autofocus => (@user == current_user),
      :value => @user == current_user ? '' : @user.username
    | for:

  = f.text_area :description,
    :placeholder => 'doing something awesome (give context with #hashtags)',
    :required => true,
    :maxlength => description_max_length,
    :autofocus => (@user != current_user)

  p #{f.submit :value => 'Broadcast it!'}

input#users type='hidden' value="#{current_user.peers.map(&:username).join(',')}"

app/views/accomplishments/index.slim
section#latest-accomplishments
  h1 Latest Accomplishments
  = will_paginate @accomplishments
  ul
    - if @accomplishments.empty?
      = image_tag 'forever-alone.png', :id => 'forever-alone', :alt => 'Forever Alone!', :title => 'Forever Alone!'
    - else
      - @accomplishments.each do |acc|
        li.accomplishment itemscope='' itemtype='http://schema.org/Review'
          div itemprop='itemReviewed' itemscope='' itemtype='http://schema.org/Person'
            = gravatar_image_tag(acc.receiver.email, itemprop:'image', alt: acc.receiver.username, gravatar: { secure: true, size: 50 })
            = link_to acc.receiver.username, user_path(acc.receiver.username), :itemprop => 'name'
          p itemprop='description' = truncate acc.description, length: 310
          time itemprop='datePublished' datetime=acc.updated_at.utc.iso8601
            span.day = acc.updated_at.day
            span.month = acc.updated_at.strftime '%b'
            span.year = acc.updated_at.year
          = link_to "by #{acc.poster.username}", user_path(acc.poster.username), :itemprop => 'author'

  = will_paginate @accomplishments